language: node_js
node_js:
- '8.12'
sudo: false
env:
  - NODE_ENV='test'
matrix:
  # this matrix runs two processes in parallel, one for android, one for iOS
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      sudo: required
      node_js: false
      before_install:
        - openssl aes-256-cbc -K $encrypted_81656b5e166a_key -iv $encrypted_81656b5e166a_iv -in secrets.tar.enc -out secrets.tar -d
        - tar xvf secrets.tar
        - nvm install node
        - node --version
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn install --frozen-lockfile
      before_deploy:
        - find . -name *.apk
      deploy:
        provider: releases
        name: $TRAVIS_TAG
        api_key:
          secure: ao6BfKCG0/QFDITW8cJ+cuHgWBP2UgOK3ONMmaLcRIih9h8ZZB5sRPL5epphUsMQVcc3p9+flUOcPGqAjC6xhk9+/MiTdk8733WmaKxAqvcEQzfoaWjAMRyOAByLYGyk1T9wCaHI5nvEQsdoxyL1i36J3QcSZ6cqbAwnFkAgJ4ovoCupNBrMC36PGMtzTNcGOQ1Vxcr+o/sxwF1ic4TbkvWCXwZmuStUvMIcjN+unXIuh9F0zcvEVVbt2ElFZkvzIdGhvWpdbOTujRldI5MgGU496sRniKY5gxVY91r2quTOG/C310RBBSmO904s8CHcT1y5R1ou+uUF0Zis0VMza/Atp3N/uPQYOjs88x6rZcqdsSjXP3XnrksdflMPuwqAI4ZbYZZ3GDveMEk58WOO24n2fGRszml+EuseB+zATDI8ZevefjjYOPQwk9IHoeSz3h0WSqnoK5/WHW+YImCPp9YZu+YMKNfrQEPlNbeKNRrsgwy3sOoOeIuUEb4MzdKPkdipggxhdck68eEU8Ynf9jWvoE6G1Ft4RIEG6ZZmYYsT3zxMHG0CbR9XW4wum/XZ+yXv7ONfQvmyo6Lf9b14fBDYScc/8gFSr3SAQAiwuLRKdf13SG3VB6uvrtz87VQg5PNdsNnG8cH5J5yFLGfERKTAZZa8b61vuD/xbD+UwZ4=
        file: "./android/app/build/outputs/apk/dev/release/app-dev-release.apk"
        skip_cleanup: true
        on:
          all_branches: true
          repo: mapswipe/mapswipe
          tags: true
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-27
      before_script:
        - yarn lint
        - yarn flow
        - yarn test
        - sudo sysctl fs.inotify.max_user_watches=524288
        - sudo sysctl -p
        - echo no | android create avd --force -n ci_avd -t android-28 --abi armeabi-v7a -c 100M
        - emulator -avd ci_avd -no-audio -no-window &
        - android-wait-for-emulator
        - adb shell input keyevent 82 &
        - detox build -c ci_avd
        - detox test -c ci_avd --loglevel trace
      script:
        - yarn buildDev
    - language: objective-c
      os: osx
      osx_image: xcode10.2
      node_js: false
      env:
      - FASTLANE_DISABLE_COLORS=1
      addons:
        ssh_known_hosts: gitlab.com
      before_install:
      - set -o pipefail
      - gem install bundler --pre
      - nvm install node
      - node --version
      - travis_retry npm install -g yarn
      - yarn -version
      # open the secret box with passwords and API keys
      - openssl aes-256-cbc -K $encrypted_81656b5e166a_key -iv $encrypted_81656b5e166a_iv -in secrets.tar.enc -out secrets.tar -d
      - tar -xvf secrets.tar
      install:
      - bundle install
      - travis_retry gem install xcpretty cocoapods
      - travis_retry yarn install --frozen-lockfile
      script:
      # calculate version numbers for fastlane
      - source ios/version-ios.sh
      # try to hide some build warnings
      - export CLANG_WARN_COMMA=NO
      - export CLANG_WARN_DOCUMENTATION=NO
      # setup RSA key so we can clone the certificate repo in gitlab
      - eval "$(ssh-agent -s)"
      - chmod 600 ./mapswipe.dev_at_gmail_rsa_key_for_travis_ci
      - ssh-add ./mapswipe.dev_at_gmail_rsa_key_for_travis_ci
      # define a custom keychain for fastlane to use
      - export KEY_CHAIN=ios-build.keychain
      - security create-keychain -p travis $KEY_CHAIN
      - security default-keychain -s $KEY_CHAIN
      - security unlock-keychain -p travis $KEY_CHAIN
      - security set-keychain-settings -t 3600 -u $KEY_CHAIN
      - cd ios
      # get the certificates from gitlab
      - bundle exec fastlane match appstore --readonly --verbose
      # always build the app to make sure that it compiles
      - bundle exec fastlane build
      before_deploy:
      deploy:
        # deploy the beta/dev build to testflight for all tagged commits
        - provider: script
          skip_cleanup: true
          script:
          - bundle exec fastlane beta --verbose
          on:
            all_branches: true
            tags: true
        # and for tagged commits to master, deploy to production
        # FIXME: this probably does not work yet
        - provider: script
          script:
          - fastlane release
          on:
            branch: master
            tags: true
